# Generated by Django 5.2.13 on 2026-05-21 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('director', 'Director'), ('auditor', 'Auditor'), ('ato', 'ATO'), ('assistant', 'Assistant')], default='admin', max_length=20),
        ),
    ]
