# Generated by Django 5.2.13 on 2026-05-08 01:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyLeagueSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PosTerminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminal_id', models.CharField(max_length=100, unique=True)),
                ('station_name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_terminals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaxEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_item', models.CharField(max_length=100)),
                ('subhead', models.CharField(max_length=100)),
                ('remita', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('interswitch_ref', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('gokollect', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('remita_verified', models.BooleanField(default=False)),
                ('interswitch_verified', models.BooleanField(default=False)),
                ('gokollect_verified', models.BooleanField(default=False)),
                ('remita_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('interswitch_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('gokollect_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('area_office', models.CharField(db_index=True, max_length=100)),
                ('taxpayer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('date_of_remittance', models.DateField(blank=True, null=True)),
                ('vehicle_type', models.CharField(blank=True, max_length=100, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=100, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=20)),
                ('source', models.CharField(choices=[('POS', 'POS'), ('Manual', 'Manual')], default='Manual', max_length=20)),
                ('data', models.JSONField(blank=True, null=True)),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_entries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('verify', 'Verified')], default='update', max_length=20)),
                ('changes', models.JSONField(help_text='Store old vs new values here')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('tax_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='tax.taxentry')),
            ],
        ),
        migrations.AddIndex(
            model_name='taxentry',
            index=models.Index(fields=['month', 'year'], name='tax_taxentr_month_7bc557_idx'),
        ),
        migrations.AddIndex(
            model_name='taxentry',
            index=models.Index(fields=['date_uploaded'], name='tax_taxentr_date_up_e752dc_idx'),
        ),
        migrations.AddIndex(
            model_name='taxentry',
            index=models.Index(fields=['date_of_remittance'], name='tax_taxentr_date_of_a107bd_idx'),
        ),
        migrations.AddIndex(
            model_name='taxentry',
            index=models.Index(fields=['source'], name='tax_taxentr_source_5f911f_idx'),
        ),
        migrations.AddIndex(
            model_name='taxentry',
            index=models.Index(fields=['tax_item'], name='tax_taxentr_tax_ite_e6d0d7_idx'),
        ),
        migrations.AddConstraint(
            model_name='taxentry',
            constraint=models.UniqueConstraint(condition=models.Q(('remita__isnull', False)), fields=('remita',), name='unique_remita_when_present'),
        ),
        migrations.AddConstraint(
            model_name='taxentry',
            constraint=models.UniqueConstraint(condition=models.Q(('interswitch_ref__isnull', False)), fields=('interswitch_ref',), name='unique_interswitch_when_present'),
        ),
        migrations.AddConstraint(
            model_name='taxentry',
            constraint=models.UniqueConstraint(condition=models.Q(('gokollect__isnull', False)), fields=('gokollect',), name='unique_gokollect_when_present'),
        ),
    ]
