# Generated by Django 5.2.13 on 2026-05-21 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=50)),
                ('terminal_id', models.CharField(max_length=100)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='success', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='posterminal',
            name='branch_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='posterminal',
            name='channel',
            field=models.CharField(choices=[('softnet', 'Softnet'), ('gokollect', 'Gokollect')], default='softnet', max_length=20),
        ),
        migrations.AddField(
            model_name='posterminal',
            name='provider',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='taxentry',
            name='pos_terminal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_entries', to='tax.posterminal'),
        ),
        migrations.AlterField(
            model_name='posterminal',
            name='terminal_id',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name='taxentry',
            index=models.Index(fields=['gokollect'], name='tax_taxentr_gokolle_fcf98e_idx'),
        ),
        migrations.AddIndex(
            model_name='taxentry',
            index=models.Index(fields=['remita'], name='tax_taxentr_remita_a5f317_idx'),
        ),
        migrations.AddIndex(
            model_name='taxentry',
            index=models.Index(fields=['interswitch_ref'], name='tax_taxentr_intersw_2f5fc7_idx'),
        ),
    ]
