# Generated by Django 5.2.13 on 2026-05-26 15:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0003_taxentry_birs_split_amount_taxentry_external_source_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='posterminal',
            name='softnet_ato_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='posterminal',
            name='softnet_ato_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='taxentry',
            name='reconciliation_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxentry',
            name='reconciliation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('matched', 'Matched'), ('amount_mismatch', 'Amount Mismatch'), ('missing_softnet', 'Missing Softnet'), ('duplicate', 'Duplicate'), ('failed', 'Failed')], default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='taxentry',
            name='softnet_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='taxentry',
            name='softnet_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='taxentry',
            name='softnet_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='taxentry',
            name='softnet_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taxentry',
            name='softnet_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='taxentry',
            index=models.Index(fields=['softnet_reference'], name='tax_taxentr_softnet_5e97bf_idx'),
        ),
        migrations.AddIndex(
            model_name='taxentry',
            index=models.Index(fields=['reconciliation_status'], name='tax_taxentr_reconci_e0915a_idx'),
        ),
        migrations.AddConstraint(
            model_name='taxentry',
            constraint=models.UniqueConstraint(condition=models.Q(('softnet_reference__isnull', False)), fields=('softnet_reference',), name='unique_softnet_reference_when_present'),
        ),
    ]
