# Generated by Django 5.2.13 on 2026-07-01 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0004_posterminal_softnet_ato_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxentry',
            name='last_verification_attempt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxentry',
            name='verification_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='taxentry',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('verified', 'Verified'), ('failed', 'Failed'), ('mismatch', 'Mismatch'), ('duplicate', 'Duplicate')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='taxentry',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
